const int CNT_NUMBER_SPRITES_WALK	= 8;
const int CNT_NUMBER_SPRITES_RUN	= 7;
const int CNT_NUMBER_SPRITES_ATTACK = 4;
const int CNT_NUMBER_SPRITES_DIE	= 4;
const int CNT_NUMBER_SPRITES_DIZZY	= 3;

#define HERO_COLLISION_BITMASK		0x000001
#define ENEMY_COLLISION_BITMASK		0x000002
#define BULLET_COLLISION_BITMASK	0x000003
#define SCENE_COLLISION_BITMASK		0x000004